### ISSUE TITLE
How do I get ONLY REQUIRED dependencies?

### ISSUE THREAD

**Issue by jmploc** [Owen-Cochell/cursepy#4]
Hi! Please excuse me for asking here.
I need to get a list of dependencies from the mod, but only those that are necessary for it to work.
`file.dependencies` gets all the dependencies that I don't need

**Comment by jmploc** [comment]
![image](https://user-images.githubusercontent.com/41044969/164142905-5e5f10a6-ccfd-40e9-a193-99a012bc4958.png)

**Comment by OwenCochell** [comment]
This feature is currently not implemented in cursepy. However, I think that it definitely should be!

Over the next week or two I will be adding official support for dependencies, and implement this in the ForgeSCV handlers(and any others that are written in the future). This will allow for dependencies to be identified as optional or required. It will also keep track of the file ID as well as the addon ID. There may be a delay, as finals are in full swing at my university, but once I get some free time then it should be pretty easy to implement this change.

In the meantime, you can access the raw data of each CurseFile instance and pull the dependency data out yourself. It's a bit janky, but if you need to determine required dependencies before I implement official support then you can do it like this:

```python
from cursepy.wrapper import CurseClient

# Create the client:

client = CurseClient()

# Get an addon file:

file = client.addon_file(ADDON_ID, FILE_ID)

# Iterate over each dependency:

for depen in file.raw['dependencies']:

    # Type of 2 is required, type of 3 is optional

    if depen['type'] == 3:
        print("Required Dependency!")
    if depen['type'] == 2:
        print("Optional Dependency!")

    print("AddonID: {} - FileID: {}".format(depen['addonId'], depen['fileId']))

```
The thing you are looking for is the 'type' field, which contains an int representing the dependency type. A dependency with a type of '3' is required, and a type of '2' is optional. You can also pull file and addon IDs out of the raw data as seen above. Again, this is not a perfect solution, and all of this functionality will be present once I implement official support.

Thank you for pointing this out! I will comment back here once I have a implemented dependency support.

**Comment by jmploc** [comment]
OK, I'll be waiting for a message from you here. Thanks!

**Comment by jmploc** [comment]
You're not right. Type 3 for required and type 2 for optional :)

**Comment by OwenCochell** [comment]
My mistake! I have updated my comment to correct the error. Thanks for pointing that out, I will be (hopefully) getting back to you soon!

**Comment by OwenCochell** [comment]
Alright, I have added some more dependency features. Dependencies are now represented by a CurseDependency class. This class contains the addon ID, file ID, and a type parameter that determines whether the addon is required or optional. You can ready up on the [CurseDependency docs](https://cursepy.readthedocs.io/en/latest/basic/curse_inst.html#cursedependency) to learn what this class does.

You can also use the upgraded 'get_dependencies()' method on the CurseFIile instance. By default, it returns all of our CurseDependency objects attributed to file, but you can have it return only optional or required dependencies by using the 'required' or 'optional' parameters. For example, to get only required dependencies:

```python
depen = file.get_dependencies(required=True)
```

Hopefully this should make working with dependencies much easier. You can upgrade cursepy via pip, the version you want is '1.2.0'. Thanks again for pointing this out!

**Comment by jmploc** [comment]
Hello. After update, I get an error: 
```
final.append(base.CurseDependency(depen['id'], depen['addonId'], depen['fileId'], depen['type']))
KeyError: 'id'
```
Error due to this line:
`for f in client.addon_files(selectedMod.id):`

**Comment by jmploc** [comment]
I can suggest adding a method that searches for the latest version of the mod for a specific version of the game and returns file id.
`getNewestFile(addon_id, game_version)`
Usage example:
`getNewestFile(518157, "1.12.2") # Output: 3763886`

**Comment by OwenCochell** [comment]
Interesting idea, I think that file searching could be an excellent feature.

However, I think we should make a new issue for this if you don't mind. If your original solution is solved, then please feel free to close this issue. We can move the conversation about file searching to a new issue.

Thanks!

**Comment by jmploc** [comment]
OK, I'll move message to new issue! Thanks!
